### ISSUE TITLE
Process deadlocked with error 'CUDA driver initialization failed, you might not have a CUDA gpu.'

### ISSUE THREAD

**Issue by UTKRISHTPATESARIA** [K-Wu/pytorch-direct_dgl#5]
```

$ python train_sampling_pytorch_direct.py

/mnt/utkrisht/miniconda3/envs/zc/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/base.py:45: DGLWarning: DEPRECATED: DGLGraph and DGLHeteroGraph have been merged in v0.5.
        dgl.as_heterograph will do nothing and can be removed safely in all cases.
  return warnings.warn(message, category=category, stacklevel=1)

Process Process-2:
Traceback (most recent call last):
  File "/mnt/utkrisht/miniconda3/envs/zc/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/mnt/utkrisht/miniconda3/envs/zc/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/utkrisht/pytorch-direct_dgl/dgl/examples/pytorch/graphsage/utils.py", line 38, in decorated_function
    raise exception.__class__(trace)
RuntimeError: Traceback (most recent call last):
  File "/mnt/utkrisht/pytorch-direct_dgl/dgl/examples/pytorch/graphsage/utils.py", line 26, in _queue_result
    res = func(*args, **kwargs)
  File "/mnt/utkrisht/pytorch-direct_dgl/dgl/examples/pytorch/graphsage/train_sampling_pytorch_direct.py", line 194, in run
    th.cuda.set_device(device)
  File "/mnt/utkrisht/miniconda3/envs/zc/lib/python3.10/site-packages/torch/cuda/__init__.py", line 257, in set_device
    torch._C._cuda_setDevice(device)
  File "/mnt/utkrisht/miniconda3/envs/zc/lib/python3.10/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.

```

- While running the example scripts the program is stuck indefinitely with the above error.
- I went through the following github link (https://github.com/pytorch/pytorch/issues/17199), but i see thread_wrap_func() has been implemented to circumvent deadlocking issue.
- Can someone please look into this?

Environment details:

```
TESLA V100 (16GB)
Python 3.10.11
dgl-0.9-py3.10

```

**Comment by UTKRISHTPATESARIA** [comment]
Hello @K-Wu @davidmin7 , can you please help me with the above issue?
